name: currency_ios
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+14

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  intl: "0.16.1"
  http: ^0.13.1
  firebase_messaging: ^9.1.2  
  #firebase_auth: ^0.18.4+1
  #cloud_firestore: ^0.14.4
  #firebase_storage: ^5.2.0
  firebase_core: ^1.0.4
  flutter_swiper : ^1.1.6
  webview_flutter: ^2.0.2
  shared_preferences: ^0.5.7+3
  #awesome_notifications: ^0.0.5+8
  #workmanager: ^0.2.3
  swipedetector: ^1.2.0
  flutter_rating_bar: ^3.2.0+1
  #flutter_automation: ^1.4.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  #in_app_purchase: ^0.3.5
  flutter_inapp_purchase: ^5.0.1
  loading_overlay: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/pin.png
    - assets/iconbtn.png
    - assets/homebtn.png
    - assets/

  fonts:
    - family: Roboto-Bold
      fonts:
        - asset: fonts/Roboto-Bold.ttf
    - family: Roboto-Light
      fonts:
        - asset: fonts/Roboto-Light.ttf
    - family: Roboto-Medium
      fonts:
        - asset: fonts/Roboto-Medium.ttf
    - family: Roboto-Regular
      fonts:
        - asset: fonts/Roboto-Regular.ttf   
    - family: awesome
      fonts:
        - asset: fonts/Font_awesome/fa-regular-400.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Font_Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: fonts/Font_Montserrat/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: fonts/Font_Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Font_Montserrat/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: fonts/Font_Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Font_Montserrat/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Font_Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Font_Montserrat/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/Font_Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Font_Montserrat/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Font_Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Font_Montserrat/Montserrat-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Font_Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Font_Montserrat/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Font_Montserrat/Montserrat-Thin.ttf
          weight: 200
        - asset: fonts/Font_Montserrat/Montserrat-ThinItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/Font_Montserrat/Montserrat-ExtraLight.ttf
          weight: 100
        - asset: fonts/Font_Montserrat/Montserrat-ExtraLightItalic.ttf
          style: italic
          weight: 100
