-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgG1sBHIBBcX4lsDAL
O7KINup0HqK0H2XMIt1zpGC4q/egCgYIKoZIzj0DAQehRANCAATIwBM04UCiSFgp
zaEB4XwiwIMNKTAn5FqS32kUbklHwOGRyWBE8nRwOciUPGL52rLrVStyOgLIyMYd
Usgz/umS
-----END PRIVATE KEY-----